// Code generated by "pug.go"; DO NOT EDIT.

package pug

import (
	pool "github.com/valyala/bytebufferpool"
)

const (
	case__0  = `<p>you have no friends1</p>`
	case__1  = `<p>you have a friend</p>`
	case__2  = `<p>you have `
	case__3  = ` friends1</p>`
	case__4  = `<p>you have very few friends2</p>`
	case__6  = ` friends2</p>`
	case__7  = `<p>you have very few friends3</p>`
	case__9  = ` friends3</p>`
	case__10 = `<p>you have no friends</p>`
	case__13 = ` friends</p>`
)

func pug_case(buffer *pool.ByteBuffer) {

	var friends1 = 10
	switch friends1 {
	case 0:
		buffer.WriteString(case__0)

	case 1:
		buffer.WriteString(case__1)

	default:
		buffer.WriteString(case__2)
		WriteInt(int64(friends1), buffer)
		buffer.WriteString(case__3)

	}
	var friends2 = 0
	switch friends2 {
	case 0:
		fallthrough
	case 1:
		buffer.WriteString(case__4)

	default:
		buffer.WriteString(case__2)
		WriteInt(int64(friends2), buffer)
		buffer.WriteString(case__6)

	}
	var friends3 = 0
	switch friends3 {
	case 0:
		break
	case 1:
		buffer.WriteString(case__7)

	default:
		buffer.WriteString(case__2)
		WriteInt(int64(friends3), buffer)
		buffer.WriteString(case__9)

	}
	var friends = 1
	switch friends {
	case 0:
		buffer.WriteString(case__10)

	case 1:
		buffer.WriteString(case__1)

	default:
		buffer.WriteString(case__2)
		WriteInt(int64(friends), buffer)
		buffer.WriteString(case__13)

	}

}
