// Code generated by "pug.go"; DO NOT EDIT.

package pug

import (
	pool "github.com/valyala/bytebufferpool"
)

const (
	code__0 = `<p>`
	code__1 = `</p><p>`
	code__4 = `</p>`
	code__5 = `<li>item</li>`
	code__6 = `<li>`
	code__7 = `</li>`
)

func pug_code(buffer *pool.ByteBuffer) {

	for i := 0; i < 3; i++ {
		buffer.WriteString(code__5)

	}

	var list = []string{"Uno", "Dos", "Tres",
		"Cuatro", "Cinco", "Seis"}
	for _, item := range list {
		buffer.WriteString(code__6)
		WriteEscString(item, buffer)
		buffer.WriteString(code__7)
	}
	buffer.WriteString(code__0)
	WriteEscString("This code is &lt;escaped&gt;!", buffer)
	buffer.WriteString(code__1)
	WriteEscString("This code is <escaped>!", buffer)
	buffer.WriteString(code__1)
	buffer.WriteString("This code is <strong>not</strong> escaped!")
	buffer.WriteString(code__1)
	buffer.WriteString("This code is <strong>not</strong> escaped!")
	buffer.WriteString(code__4)

}
