// Code generated by "pug.go"; DO NOT EDIT.

package pug

import (
	pool "github.com/valyala/bytebufferpool"
)

const (
	conditionals__0 = `<div id="user">`
	conditionals__1 = `</div>`
	conditionals__2 = `<h2 class="green">Description</h2><p class="description">`
	conditionals__4 = `<h2 class="blue">Description</h2><p class="description">      User has no description,
      why not add one...</p>`
	conditionals__5 = `<h2 class="red">Description</h2><p class="description">User has no description</p>`
	conditionals__6 = `<p>You're logged in as `
)

func pug_conditionals(buffer *pool.ByteBuffer) {

	var user = struct {
		description, name string
		isAnonymous       bool
	}{description: "foo bar baz", name: "zxc"}
	var authorised = false
	buffer.WriteString(conditionals__0)
	if len(user.description) > 0 {
		buffer.WriteString(conditionals__2)
		WriteEscString(user.description, buffer)
		buffer.WriteString(code__4)
	} else if authorised {
		buffer.WriteString(conditionals__4)

	} else {
		buffer.WriteString(conditionals__5)

	}
	buffer.WriteString(conditionals__1)
	if !user.isAnonymous {
		buffer.WriteString(conditionals__6)
		WriteEscString(user.name, buffer)
		buffer.WriteString(code__4)
	}
	if !user.isAnonymous {
		buffer.WriteString(conditionals__6)
		WriteEscString(user.name, buffer)
		buffer.WriteString(code__4)
	}

}
