// Code generated by "pug.go"; DO NOT EDIT.

package pug

import (
	pool "github.com/valyala/bytebufferpool"
)

const (
	doctype__0 = `<!DOCTYPE html><!DOCTYPE html><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML Basic 1.1//EN"><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"><!DOCTYPE html>`
)

func pug_doctype(buffer *pool.ByteBuffer) {

	buffer.WriteString(doctype__0)

}
