// Code generated by "pug.go"; DO NOT EDIT.

package pug

import (
	pool "github.com/valyala/bytebufferpool"
)

const (
	filters__0 = `<p></p><p>    In the midst of a large amount of plain
    text, suddenly a wild <appeared>
</appeared></p><script></script><p><div><div id="function"></div></div></p>`
)

func Output(user string, buffer *pool.ByteBuffer) {

	buffer.WriteString(filters__0)

}
