// Code generated by "pug.go"; DO NOT EDIT.

package pug

import (
	"strings"

	pool "github.com/valyala/bytebufferpool"
)

const (
	interpolation__0 = `<h1>`
	interpolation__1 = `</h1><p>Written with love by `
	interpolation__2 = `</p><p>This will be safe: `
	interpolation__4 = `<p>This is `
	interpolation__5 = `</p><p>No escaping for `
	interpolation__6 = `!</p><p>Escaping works with \#{interpolation}</p><p>Interpolation works with `
	interpolation__7 = ` too!</p>`
	interpolation__8 = `<div class="quote"><p>Joel: `
	interpolation__9 = `</p></div><p>  This is a very long and boring paragraph that spans multiple lines.
  Suddenly there is a <strong>strongly worded phrase</strong> that cannot be
  <em>ignored</em>.</p><p>  And here's an example of an interpolated tag with an attribute:
  <q lang="es">¡Hola Mundo!</q>

</p><p>If I don't write the paragraph with tag interpolation, tags like<strong>strong</strong>and<em>em</em>might produce unexpected results.</p><p>  If I do, whitespace is <strong>respected</strong> and <em>everybody</em> is happy.
</p>`
)

func pug_interpolation(buffer *pool.ByteBuffer) {

	var title = "On Dogs: Man's Best Friend"
	var author = "enlore"
	var theGreat = "<span>escape!</span>"
	buffer.WriteString(interpolation__0)
	WriteEscString(title, buffer)
	buffer.WriteString(interpolation__1)
	WriteEscString(author, buffer)
	buffer.WriteString(interpolation__2)
	WriteEscString(theGreat, buffer)
	buffer.WriteString(code__4)
	var msg = "not my inside voice"
	buffer.WriteString(interpolation__4)
	WriteAll(strings.ToUpper(msg), true, buffer)
	buffer.WriteString(interpolation__5)
	WriteEscString("}", buffer)
	buffer.WriteString(interpolation__6)
	WriteEscString("#{interpolation}", buffer)
	buffer.WriteString(interpolation__7)

	var riskyBusiness = "<em>Some of the girls are wearing my mother's clothing.</em>"
	buffer.WriteString(interpolation__8)
	buffer.WriteString(riskyBusiness)
	buffer.WriteString(interpolation__9)

}
