// Code generated by "pug.go"; DO NOT EDIT.

package pug

import (
	pool "github.com/valyala/bytebufferpool"
)

func pug_tags(buffer *pool.ByteBuffer) {

	buffer.WriteString(`<ul><li>Item A</li><li>Item B</li><li>Item C</li></ul><img/><a><img/></a><foo/><foo bar="baz"/>`)

}
