// Code generated by "pug.go"; DO NOT EDIT.

package pug

import (
	pool "github.com/valyala/bytebufferpool"
)

func pug_layoutb(buffer *pool.ByteBuffer) {

	buffer.WriteString(`<html><head><script src="/vendor/jquery.js"></script><script src="/vendor/caustic.js"></script></head><body></body></html>`)

}
