// Code generated by "pug.go"; DO NOT EDIT.

package pug

import (
	pool "github.com/valyala/bytebufferpool"
)

func pug_pet(petName string, buffer *pool.ByteBuffer) {

	buffer.WriteString(`<p>`)
	WriteEscString(petName, buffer)
	buffer.WriteString(`</p>`)

}
