name: Go Report Card

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Go Report Card
      uses: creekorful/goreportcard-action@v1.0