name: Go Report Card

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Go Report Card
      uses: creekorful/goreportcard-action@v1.0